-- MySQL Script generated by MySQL Workbench
-- Sun Nov  4 13:50:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema obd/gps-datenlogger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema obd/gps-datenlogger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obd/gps-datenlogger`;
USE `obd/gps-datenlogger` ;

-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`data`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`data` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(180) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `starttime` VARCHAR(45) NULL DEFAULT NULL,
  `totalKM` FLOAT NULL DEFAULT NULL,
  `endtime` VARCHAR(45) NULL DEFAULT NULL,
  `VIN` VARCHAR(20) NULL DEFAULT NULL,
  `fuelConsumption` FLOAT NULL DEFAULT NULL,
  `energyConsumption` FLOAT NULL DEFAULT NULL,
  `endLat` FLOAT NULL DEFAULT NULL,
  `endLong` FLOAT NULL DEFAULT NULL,
  `endDate` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC)
);

-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`)
);

-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` BINARY(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC)
);
