-- MySQL Script generated by MySQL Workbench
-- Sun Nov  4 13:50:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema obd/gps-datenlogger
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema obd/gps-datenlogger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `obd/gps-datenlogger` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `obd/gps-datenlogger` ;

-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`gpsdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`gpsdata` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `route_name` VARCHAR(50) NULL DEFAULT NULL,
  `lat` FLOAT NULL DEFAULT NULL,
  `lng` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idgps-data_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`importobd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`importobd` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(45) NULL DEFAULT NULL,
  `speed` INT(11) NULL DEFAULT NULL,
  `rpm` DOUBLE NULL DEFAULT NULL,
  `engine_load` DOUBLE NULL DEFAULT NULL,
  `maf` DOUBLE NULL DEFAULT NULL,
  `temperature` INT(11) NULL DEFAULT NULL,
  `pedal` DOUBLE NULL DEFAULT NULL,
  `afr` DOUBLE NULL DEFAULT NULL,
  `fuel_level` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT(11) UNSIGNED NOT NULL,
  `data` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `obd/gps-datenlogger`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `obd/gps-datenlogger`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `password` BINARY(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
